on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [aws-lambda-http, aws-lambda-custom-runtime, aws-lambda-events, bearer-auth, graalvm, hello-world, hexagonal, hotwire, http4k-connect, graphql, json-api, oauth, openapi, quarkus, react-app, typesafe-configuration, web-content, websockets]
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: pushd ${{ matrix.project }} && ./gradlew test
      - name: Tag automerge branch
        if: ${{ github.event_name == 'pull_request' }}
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PUBLIC_REPO_RELEASE_TRIGGERING }}


